config/routes.rb
SocialTennis::Application.routes.draw do
  resources :users

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'

  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  dob             :date
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  include Gravtastic
  gravtastic
  attr_accessible :dob, :email, :name, :password, :password_confirmation
  has_secure_password


  before_save { |user| user.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  validates :dob, allow_blank: true, timeliness: { type: :date }
  after_validation { self.errors.messages.delete(:password_digest) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis
  def full_title(page_title)
    base_title = "Social Tennis"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    | by 
    a href="http://filippos.vasilak.is" Filippos Vasilakis
  nav
    ul
      li= link_to 'About', about_path
      li= link_to 'Contact', contact_path

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "Social Tennis", root_path, id: 'logo'
      nav
        ul.nav.pull-right
          li= link_to "Home", root_path
          li= link_to "About", about_path
          li= link_to "Sign in", '#'

app/views/layouts/_shim.html.slim
/![if lt IE 9] 
  | <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.slim
doctype 5
html
  head
    title= full_title(yield(:title))
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        .alert class="alert-#{key}"
          = value
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?

app/views/shared/_error_messages.html.slim
- if @user.errors.any?
  #error_explanation
    .alert.alert-error
      | This form contains #{pluralize(@user.errors.count, "error")}.
    ul
      - @user.errors.full_messages.each do |msg|
        li
          | * #{msg}

app/views/static_pages/about.html.slim
-provide(:title, 'About')
h1 About
p
  | Find me in app/views/static_pages/help.html.erb

app/views/static_pages/contact.html.slim
-provide(:title, 'Contact')
h1 Contact Us
p
  | This is a contact page

app/views/static_pages/home.html.slim
-provide(:title, 'Home')
.center.hero-unit
  h1 Welcome to Social Tennis
  h2
    | If you always wanted to be treated just like a professional tennis
    |  player this place is build just for you!

  h5
    | Get stats for your performance, bla bla bla bla bla bla bla bla
  br
  br
  p
    = link_to "Sign up now", signup_path, class: "btn btn-large btn-primary"
  p and challenge another player!

app/views/users/create.html.slim
h1 Users#create
p Find me in app/views/users/create.html.slim

app/views/users/new.html.slim
-provide(:title, 'Sign Up')
h1 Sign Up
.row
  .span6.offset3
    = form_for(@user) do |f|
      = render 'shared/error_messages'

      = f.label :name
      = f.text_field :name

      = f.label :email
      = f.text_field :email

      = f.label :password
      = f.password_field :password

      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation

      = f.submit "Create my account", class: "btn btn-large btn-primary"

app/views/users/show.html.slim
-provide(:title, @user.name)
div.row
  aside.span4
    section
      h1
        = image_tag(@user.gravatar_url, alt: @user.name, class: "gravatar")
        = @user.name